### ISSUE TITLE
Shell scripts need to check return code

### ISSUE THREAD

**Issue by montjoie** [lucj/kernelci-docker#12]
When running ./start.sh 
-> deploying the application...
unsupported Compose file version: 3.4
-> application deployed

All docker (and other important) command should have some || exit $?

**Comment by lucj** [comment]
What is the Docker daemon version you are running ?

**Comment by montjoie** [comment]
Version:      17.06.2-ce
But this bug is unrelated to version

**Comment by lucj** [comment]
Version 3.4 of a Docker Compose file is not supported for version below 17.09.0
(https://docs.docker.com/compose/compose-file/#reference-and-guidelines), so this error is related but you are right, exit need to be added however

**Comment by lucj** [comment]
btw, version 17.06.2 is not in the list of the version already tested listed in the README, I'm not sure this will work as expected then.

**Comment by lucj** [comment]
Fixed with https://github.com/lucj/kernelci-docker/pull/14
