### ISSUE TITLE
Handling TLS termination

### ISSUE THREAD

**Issue by lucj** [lucj/kernelci-docker#13]
Following a discussion with Kevin:

Our client is having some issues setting up kernelci-docker while using https.
Could you do a test setup with https, and document any settings/changes that might be needed?
In particular, they terminate https using some AWS load balancer thingy, then pass everything to kernelci-docker port 8080.
The frontend is visible, but seems some URLs between front and back are http:// which seems to be causing problems for them.
Maybe a simple example using a letsencrypt.org cert with an nginx reverse proxy in front of the frontend/backend or something similar?  That would be quite useful. (edited)

**Comment by lucj** [comment]
@khilman @loysollivier could you provide examples of URL which fails ? I guess those are URLs directly targeting the api from the outside, right ?

**Comment by khilman** [comment]
The LF install is here: https://kernelci.automotivelinux.org/
If you try https://kernelci.automotivelinux.org/soc/broadcom/, you'll see an error.   Looking in the dev console of chrome, I see this:
`Mixed Content: The page at 'https://kernelci.automotivelinux.org/soc/broadcom/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://kernelci.automotivelinux.org/_ajax/boot/distinct/board/?mach=broadcom'. This request has been blocked; the content must be served over HTTPS.`

**Comment by lucj** [comment]
In the _makeRequest function, in ./frontend/kernelci-frontend/app/dashboard/static/js/app/utils/request.js, is responsible for building the ajax request and for sending it over to the api.

```
function _makeRequest(method, url, data) {
    settings.headers = {'Content-Type': 'application/json'};
    settings.type = method;
    if (!data) {
        data = {};
    }
    settings.data = data;
    return $.ajax(url, settings);
}
```

Exemple of an url provided to this function: '/_ajax/boot/distinct/board/'

I'm not 100% sure but I guess providing the current URL (window.location.href + url) could fix the thing as the current protocol will be used. 

I'll try this modification locally in the frontend and make sure it does not do any harm when TLS is not involved. Then I can check when the application is served behind a TLS termination.

**Comment by khilman** [comment]
@lucj any chance of your suggestion in the form of a patch/commit for testing?  I'm not familiar enough with the code (or with javascript) to turn your idea into code.

**Comment by lucj** [comment]
@loysollivier do you think you could try this fix on your local install of kernelci and check if this causes regressions on the "non https" UI ?

**Comment by loysollivier** [comment]
@lucj yes I intend to try it. But I need to fix my "nodemon" error when using dev-start.sh first (CF. Slack).

**Comment by khilman** [comment]
kernelci.dev.baylibre.com:8080 is now running the master branch of the kernelci frontend and backend, and started using `dev-start.sh`.  
In addition, I've added the above suggestion in the form of the patch below, but not exactly sure how to fully test it.

```
diff --git a/app/dashboard/static/js/app/utils/request.js b/app/dashboard/static/js/app/utils/request.js
index 467fd0f..cd5d960 100644
--- a/app/dashboard/static/js/app/utils/request.js
+++ b/app/dashboard/static/js/app/utils/request.js
@@ -53,7 +53,7 @@ define([
         }
         settings.data = data;
 
-        return $.ajax(url, settings);
+        return $.ajax(window.location.href + url, settings);
     }
 
     request.get = function(url, data) {
```

**Comment by lucj** [comment]
Route modified in frontend/app/dashboard/static/js/app/view-socs-soc.2018.2.js, so this fixes the redirection issue when behind a TLS proxy.
```
deferred = r.get('/_ajax/boot/distinct/board/', data);
```
instead of
```
deferred = r.get('/_ajax/boot/distinct/board', data);
```
(trailing slash added to the route)
